---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
platforms:
  - name: system-network-ubuntu18
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu18
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    capabilities: ['NET_ADMIN']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: system-network-ubuntu20
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu20
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    capabilities: ['NET_ADMIN']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: system-network-ubuntu22
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu22
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: system-network-debian10
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian10
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: system-network-debian11
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian11
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: system-network-oraclelinux7
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:oraclelinux7
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: system-network-oraclelinux8
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:oraclelinux8
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: system-network-oraclelinux9
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:oraclelinux9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3.9"

verifier:
  name: goss
